name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build with Buildozer
      uses: ArtemSydoryk/buildozer-action@v1
      with:
        command: buildozer android debug
        subfolder: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WillyClientSync-APK
        path: bin/*.apk
