name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Buildizer Action
      uses: Joshour/buildozer-action@v1.3.0
      with:
        command: buildozer android debug
        subfolder: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WillyClientSync-APK
        path: bin/*.apk
